/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppGraphRouteImport } from './routes/_app.graph'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppRecommendationsRouteImport } from './routes/_app.recommendations'
import { Route as AppResumeAuditRouteImport } from './routes/_app.resume-audit'
import { Route as AppRoadmapRouteImport } from './routes/_app.roadmap'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppTimelineRouteImport } from './routes/_app.timeline'
import { Route as AuthNeonCallbackRouteImport } from './routes/auth.neon-callback'
import { Route as AuthSigninRouteImport } from './routes/auth.signin'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeAuditRoute = AppResumeAuditRouteImport.update({
  id: '/resume-audit',
  path: '/resume-audit',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AuthNeonCallbackRoute = AuthNeonCallbackRouteImport.update({
  id: '/auth/neon-callback',
  path: '/auth/neon-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/onboarding': typeof OnboardingRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/graph': typeof AppGraphRoute
  '/portfolio': typeof AppPortfolioRoute
  '/projects': typeof AppProjectsRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/resume-audit': typeof AppResumeAuditRoute
  '/roadmap': typeof AppRoadmapRoute
  '/settings': typeof AppSettingsRoute
  '/timeline': typeof AppTimelineRoute
  '/auth/neon-callback': typeof AuthNeonCallbackRoute
  '/auth/signin': typeof AuthSigninRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/onboarding': typeof OnboardingRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/graph': typeof AppGraphRoute
  '/portfolio': typeof AppPortfolioRoute
  '/projects': typeof AppProjectsRoute
  '/recommendations': typeof AppRecommendationsRoute
  '/resume-audit': typeof AppResumeAuditRoute
  '/roadmap': typeof AppRoadmapRoute
  '/settings': typeof AppSettingsRoute
  '/timeline': typeof AppTimelineRoute
  '/auth/neon-callback': typeof AuthNeonCallbackRoute
  '/auth/signin': typeof AuthSigninRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/graph': typeof AppGraphRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/recommendations': typeof AppRecommendationsRoute
  '/_app/resume-audit': typeof AppResumeAuditRoute
  '/_app/roadmap': typeof AppRoadmapRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/auth/neon-callback': typeof AuthNeonCallbackRoute
  '/auth/signin': typeof AuthSigninRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/onboarding'
    | '/chat'
    | '/dashboard'
    | '/graph'
    | '/portfolio'
    | '/projects'
    | '/recommendations'
    | '/resume-audit'
    | '/roadmap'
    | '/settings'
    | '/timeline'
    | '/auth/neon-callback'
    | '/auth/signin'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/onboarding'
    | '/chat'
    | '/dashboard'
    | '/graph'
    | '/portfolio'
    | '/projects'
    | '/recommendations'
    | '/resume-audit'
    | '/roadmap'
    | '/settings'
    | '/timeline'
    | '/auth/neon-callback'
    | '/auth/signin'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/onboarding'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/graph'
    | '/_app/portfolio'
    | '/_app/projects'
    | '/_app/recommendations'
    | '/_app/resume-audit'
    | '/_app/roadmap'
    | '/_app/settings'
    | '/_app/timeline'
    | '/auth/neon-callback'
    | '/auth/signin'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthNeonCallbackRoute: typeof AuthNeonCallbackRoute
  AuthSigninRoute: typeof AuthSigninRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/graph': {
      id: '/_app/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recommendations': {
      id: '/_app/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resume-audit': {
      id: '/_app/resume-audit'
      path: '/resume-audit'
      fullPath: '/resume-audit'
      preLoaderRoute: typeof AppResumeAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/neon-callback': {
      id: '/auth/neon-callback'
      path: '/auth/neon-callback'
      fullPath: '/auth/neon-callback'
      preLoaderRoute: typeof AuthNeonCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGraphRoute: typeof AppGraphRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppResumeAuditRoute: typeof AppResumeAuditRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTimelineRoute: typeof AppTimelineRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGraphRoute: AppGraphRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppResumeAuditRoute: AppResumeAuditRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTimelineRoute: AppTimelineRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  OnboardingRoute: OnboardingRoute,
  AuthNeonCallbackRoute: AuthNeonCallbackRoute,
  AuthSigninRoute: AuthSigninRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
